/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        accent: "var(--accent)",
        "accent-soft": "var(--accent-soft)",
        "accent-ink": "var(--accent-ink)",
        "ink-strong": "var(--ink-strong)",
        "on-strong": "var(--on-strong)",
        sidebar: "var(--sidebar-bg)",
        surface: "var(--surface)",
        "surface-2": "var(--surface-2)",
        canvas: "var(--canvas)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        ink: "var(--ink)",
        muted: "var(--muted)",
        "muted-2": "var(--muted-2)",
        success: "#16A34A",
        warning: "#946E00",
        danger: "#BA1A1A",
        info: "#0058BE",
        slate: "#404848",
        // Tinted chip palette (bg / fg pairs used by IconChip/StatusPill/Avatar) —
        // remapped to sit inside the AssetFlow "sage & cream" design system
        // (see DESIGN.md from the Stitch export): teal primary, blue secondary,
        // yellow/tertiary for warnings, green for positive/active states.
        "chip-blue-bg": "#D8E2FF",
        "chip-blue-fg": "#004395",
        "chip-purple-bg": "#EBE3FB",
        "chip-purple-fg": "#5B3FA8",
        "chip-cyan-bg": "#DCF3F1",
        "chip-cyan-fg": "#1C6F68",
        "chip-orange-bg": "#FFE8C7",
        "chip-orange-fg": "#7A4A00",
        "chip-green-bg": "#DCFCE7",
        "chip-green-fg": "#166534",
        "chip-pink-bg": "#FFDAD6",
        "chip-pink-fg": "#93000A",
        "chip-yellow-bg": "#FFDF9F",
        "chip-yellow-fg": "#5C4300",
        "chip-slate-bg": "#EAE7E7",
        "chip-slate-fg": "#404848",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      fontWeight: {
        thin: "200",
        extralight: "250",
        light: "300",
        book: "350",
        normal: "400",
        medium: "500",
        semibold: "600",
      },
      borderRadius: {
        DEFAULT: "10px",
        xl: "12px",
        "2xl": "20px",
        "3xl": "28px",
        card: "24px",
      },
      boxShadow: {
        card: "0px 10px 30px rgba(26, 26, 26, 0.05)",
        "card-lg": "0px 16px 40px rgba(26, 26, 26, 0.08)",
        sidebar: "0px 20px 40px rgba(0, 0, 0, 0.18)",
        pop: "0 8px 24px rgba(15, 23, 42, 0.10)",
        inner: "inset 0 1px 2px rgba(15, 23, 42, 0.05)",
        pressed: "inset 0px 3px 6px rgba(0, 0, 0, 0.10)",
      },
    },
  },
  plugins: [],
};
