/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        accent: "var(--accent)",
        "accent-soft": "var(--accent-soft)",
        "accent-ink": "var(--accent-ink)",
        "on-accent": "var(--on-accent)",
        "ink-strong": "var(--ink-strong)",
        "on-strong": "var(--on-strong)",
        sidebar: "var(--sidebar-bg)",
        surface: "var(--surface)",
        "surface-2": "var(--surface-2)",
        canvas: "var(--canvas)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        ink: "var(--ink)",
        muted: "var(--muted)",
        "muted-2": "var(--muted-2)",
        success: "rgb(var(--success) / <alpha-value>)",
        warning: "rgb(var(--warning) / <alpha-value>)",
        danger: "rgb(var(--danger) / <alpha-value>)",
        info: "rgb(var(--info) / <alpha-value>)",
        slate: "#404848",
        // Tinted chip palette (bg / fg pairs used by IconChip/StatusPill/Avatar) —
        // remapped to sit inside the AssetFlow "sage & cream" design system
        // (see DESIGN.md from the Stitch export): teal primary, blue secondary,
        // yellow/tertiary for warnings, green for positive/active states.
        "chip-blue-bg": "rgb(var(--chip-blue-bg) / <alpha-value>)",
        "chip-blue-fg": "rgb(var(--chip-blue-fg) / <alpha-value>)",
        "chip-purple-bg": "rgb(var(--chip-purple-bg) / <alpha-value>)",
        "chip-purple-fg": "rgb(var(--chip-purple-fg) / <alpha-value>)",
        "chip-cyan-bg": "rgb(var(--chip-cyan-bg) / <alpha-value>)",
        "chip-cyan-fg": "rgb(var(--chip-cyan-fg) / <alpha-value>)",
        "chip-orange-bg": "rgb(var(--chip-orange-bg) / <alpha-value>)",
        "chip-orange-fg": "rgb(var(--chip-orange-fg) / <alpha-value>)",
        "chip-green-bg": "rgb(var(--chip-green-bg) / <alpha-value>)",
        "chip-green-fg": "rgb(var(--chip-green-fg) / <alpha-value>)",
        "chip-pink-bg": "rgb(var(--chip-pink-bg) / <alpha-value>)",
        "chip-pink-fg": "rgb(var(--chip-pink-fg) / <alpha-value>)",
        "chip-yellow-bg": "rgb(var(--chip-yellow-bg) / <alpha-value>)",
        "chip-yellow-fg": "rgb(var(--chip-yellow-fg) / <alpha-value>)",
        "chip-slate-bg": "rgb(var(--chip-slate-bg) / <alpha-value>)",
        "chip-slate-fg": "rgb(var(--chip-slate-fg) / <alpha-value>)",
        // Fixed light pastels for dark: classes that want a light tint on dark
        // surfaces (the *-bg tokens themselves turn dark in dark mode).
        "chip-blue-tint": "#D8E2FF",
        "chip-purple-tint": "#EBE3FB",
        "chip-cyan-tint": "#DCF3F1",
        "chip-orange-tint": "#FFE8C7",
        "chip-green-tint": "#DCFCE7",
        "chip-pink-tint": "#FFDAD6",
        "chip-yellow-tint": "#FFDF9F",
        "chip-slate-tint": "#EAE7E7",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      fontWeight: {
        thin: "200",
        extralight: "250",
        light: "300",
        book: "350",
        normal: "400",
        medium: "500",
        semibold: "600",
      },
      borderRadius: {
        DEFAULT: "10px",
        xl: "12px",
        "2xl": "20px",
        "3xl": "28px",
        card: "24px",
      },
      boxShadow: {
        card: "0px 10px 30px rgba(26, 26, 26, 0.05)",
        "card-lg": "0px 16px 40px rgba(26, 26, 26, 0.08)",
        sidebar: "0px 20px 40px rgba(0, 0, 0, 0.18)",
        pop: "0 8px 24px rgba(15, 23, 42, 0.10)",
        inner: "inset 0 1px 2px rgba(15, 23, 42, 0.05)",
        pressed: "inset 0px 3px 6px rgba(0, 0, 0, 0.10)",
      },
    },
  },
  plugins: [],
};
