/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
      // Landing page ("Luminous Spectrum" design system). The design's own
      // `surface` and radius tokens are omitted so they don't clash with the app's.
        "on-secondary-container": "#fefcff",
        "outline-variant": "#c9c3d8",
        "secondary-fixed": "#dae2ff",
        "surface-dim": "#d7d8ef",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#1c0062",
        "inverse-surface": "#2d2f41",
        "primary-container": "#7957ff",
        "primary-fixed-dim": "#cabeff",
        "tertiary-fixed": "#8cf2ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        "on-background": "#181b2b",
        "on-surface-variant": "#484555",
        "secondary": "#0053ce",
        "inverse-on-surface": "#f0efff",
        "inverse-primary": "#cabeff",
        "tertiary": "#006871",
        "tertiary-container": "#00838e",
        "tertiary-fixed-dim": "#2fdaeb",
        "primary-fixed": "#e6deff",
        "on-secondary-fixed": "#001848",
        "on-tertiary-fixed-variant": "#004f56",
        "primary": "#6039e5",
        "on-tertiary-container": "#ffffff",
        "surface-container-highest": "#e0e1f8",
        "surface-tint": "#613ae6",
        "surface-bright": "#fbf8ff",
        "surface-container-low": "#f3f2ff",
        "secondary-fixed-dim": "#b2c5ff",
        "on-error": "#ffffff",
        "surface-variant": "#e0e1f8",
        "on-primary-fixed-variant": "#4810ce",
        "on-secondary-fixed-variant": "#0040a2",
        "on-tertiary-fixed": "#001f23",
        "background": "#fbf8ff",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "secondary-container": "#266cf3",
        "on-error-container": "#93000a",
        "outline": "#797587",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e5e6fe",
        "on-surface": "#181b2b",
        "error-container": "#ffdad6",
        "surface-container": "#ececff",
        accent: "var(--accent)",
        "accent-soft": "var(--accent-soft)",
        "accent-ink": "var(--accent-ink)",
        "on-accent": "var(--on-accent)",
        "ink-strong": "var(--ink-strong)",
        "on-strong": "var(--on-strong)",
        sidebar: "var(--sidebar-bg)",
        surface: "var(--surface)",
        "surface-2": "var(--surface-2)",
        canvas: "var(--canvas)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        ink: "var(--ink)",
        muted: "var(--muted)",
        "muted-2": "var(--muted-2)",
        success: "rgb(var(--success) / <alpha-value>)",
        warning: "rgb(var(--warning) / <alpha-value>)",
        danger: "rgb(var(--danger) / <alpha-value>)",
        info: "rgb(var(--info) / <alpha-value>)",
        slate: "#404848",
        // Tinted chip palette (bg / fg pairs used by IconChip/StatusPill/Avatar) —
        // remapped to sit inside the AssetFlow "sage & cream" design system
        // (see DESIGN.md from the Stitch export): teal primary, blue secondary,
        // yellow/tertiary for warnings, green for positive/active states.
        "chip-blue-bg": "rgb(var(--chip-blue-bg) / <alpha-value>)",
        "chip-blue-fg": "rgb(var(--chip-blue-fg) / <alpha-value>)",
        "chip-purple-bg": "rgb(var(--chip-purple-bg) / <alpha-value>)",
        "chip-purple-fg": "rgb(var(--chip-purple-fg) / <alpha-value>)",
        "chip-cyan-bg": "rgb(var(--chip-cyan-bg) / <alpha-value>)",
        "chip-cyan-fg": "rgb(var(--chip-cyan-fg) / <alpha-value>)",
        "chip-orange-bg": "rgb(var(--chip-orange-bg) / <alpha-value>)",
        "chip-orange-fg": "rgb(var(--chip-orange-fg) / <alpha-value>)",
        "chip-green-bg": "rgb(var(--chip-green-bg) / <alpha-value>)",
        "chip-green-fg": "rgb(var(--chip-green-fg) / <alpha-value>)",
        "chip-pink-bg": "rgb(var(--chip-pink-bg) / <alpha-value>)",
        "chip-pink-fg": "rgb(var(--chip-pink-fg) / <alpha-value>)",
        "chip-yellow-bg": "rgb(var(--chip-yellow-bg) / <alpha-value>)",
        "chip-yellow-fg": "rgb(var(--chip-yellow-fg) / <alpha-value>)",
        "chip-slate-bg": "rgb(var(--chip-slate-bg) / <alpha-value>)",
        "chip-slate-fg": "rgb(var(--chip-slate-fg) / <alpha-value>)",
        // Fixed light pastels for dark: classes that want a light tint on dark
        // surfaces (the *-bg tokens themselves turn dark in dark mode).
        "chip-blue-tint": "#D8E2FF",
        "chip-purple-tint": "#EBE3FB",
        "chip-cyan-tint": "#DCF3F1",
        "chip-orange-tint": "#FFE8C7",
        "chip-green-tint": "#DCFCE7",
        "chip-pink-tint": "#FFDAD6",
        "chip-yellow-tint": "#FFDF9F",
        "chip-slate-tint": "#EAE7E7",
      },
      spacing: {
        "space-2xs": "0.125rem",
        "space-sm": "0.5rem",
        "margin-tablet": "1.5rem",
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "gutter-tablet": "1rem",
        "space-3xl": "4rem",
        "space-2xl": "3rem",
        "gutter-mobile": "0.75rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
        "margin-mobile": "1rem",
        "margin": "2rem",
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      fontFamily: {
        "body-sm": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      fontWeight: {
        thin: "200",
        extralight: "250",
        light: "300",
        book: "350",
        normal: "400",
        medium: "500",
        semibold: "600",
      },
      borderRadius: {
        DEFAULT: "10px",
        xl: "12px",
        "2xl": "20px",
        "3xl": "28px",
        card: "24px",
      },
      boxShadow: {
        card: "0px 10px 30px rgba(26, 26, 26, 0.05)",
        "card-lg": "0px 16px 40px rgba(26, 26, 26, 0.08)",
        sidebar: "0px 20px 40px rgba(0, 0, 0, 0.18)",
        pop: "0 8px 24px rgba(15, 23, 42, 0.10)",
        inner: "inset 0 1px 2px rgba(15, 23, 42, 0.05)",
        pressed: "inset 0px 3px 6px rgba(0, 0, 0, 0.10)",
      },
    },
  },
  plugins: [],
};
