const express = require("express")
const { requireAuth } = require("../middleware/auth.middleware")
const c = require("../controllers/biometric.controller")
const { requireFeature } = require("../utils/platform")
const router = express.Router()
const biometricFeature = requireFeature("biometric")
router.get("/devices", requireAuth, biometricFeature, c.listDevices)
router.post("/devices", requireAuth, biometricFeature, c.createDevice)
router.patch("/devices/:id", requireAuth, biometricFeature, c.updateDevice)
router.delete("/devices/:id", requireAuth, biometricFeature, c.deleteDevice)
router.post("/devices/:id/rotate-token", requireAuth, biometricFeature, c.rotateToken)
router.get("/devices/:id/mappings", requireAuth, biometricFeature, c.listMappings)
router.post("/devices/:id/mappings", requireAuth, biometricFeature, c.mapEmployee)
router.delete("/devices/:id/mappings/:mappingId", requireAuth, biometricFeature, c.deleteMapping)
router.get("/connector/config", c.connectorAuth, c.connectorConfig)
router.post("/connector/heartbeat", c.connectorAuth, c.heartbeat)
router.post("/connector/punches", c.connectorAuth, c.ingestPunches)
module.exports = router
