const express = require("express")
const { requireAuth } = require("../middleware/auth.middleware")
const c = require("../controllers/biometric.controller")
const router = express.Router()
router.get("/devices", requireAuth, c.listDevices)
router.post("/devices", requireAuth, c.createDevice)
router.patch("/devices/:id", requireAuth, c.updateDevice)
router.delete("/devices/:id", requireAuth, c.deleteDevice)
router.post("/devices/:id/rotate-token", requireAuth, c.rotateToken)
router.get("/devices/:id/mappings", requireAuth, c.listMappings)
router.post("/devices/:id/mappings", requireAuth, c.mapEmployee)
router.get("/connector/config", c.connectorAuth, c.connectorConfig)
router.post("/connector/heartbeat", c.connectorAuth, c.heartbeat)
router.post("/connector/punches", c.connectorAuth, c.ingestPunches)
module.exports = router
