import { useMemo, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { CalendarDays, ChevronLeft, ChevronRight, Plus, X } from "lucide-react"
import { useAuth } from "../context/AuthContext"
import api from "../api/client"
import PageHeader from "../components/ui/PageHeader"

const TYPES = { BIRTHDAY:"Birthday", PROJECT_DEADLINE:"Project deadline", NATIONAL_HOLIDAY:"Holiday", EMPLOYEE_LEAVE:"Leave", ANNUAL_EVENT:"Company event" }
const fmt = d => new Date(`${d}T00:00:00Z`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric",timeZone:"UTC"})
export default function AdvancedCalendar(){
  const {user}=useAuth(); const qc=useQueryClient(); const [cursor,setCursor]=useState(()=>new Date()); const [selected,setSelected]=useState(null); const [open,setOpen]=useState(false)
  const year=cursor.getFullYear(), month=cursor.getMonth()
  const q=useQuery({queryKey:["advanced-calendar",year,month],queryFn:()=>api.get("/dashboard/events",{params:{range:"month",year,month}}).then(r=>r.data)})
  const days=new Date(year,month+1,0).getDate(), first=new Date(year,month,1).getDay(); const cells=Array.from({length:Math.ceil((first+days)/7)*7},(_,i)=>{const d=i-first+1;return d>0&&d<=days?d:null})
  const byDate=useMemo(()=>{const m={};(q.data?.calendar||[]).forEach(e=>(m[e.date]??=[]).push(e));return m},[q.data])
  const create=useMutation({mutationFn:form=>api.post("/dashboard/events",form),onSuccess:()=>{qc.invalidateQueries({queryKey:["advanced-calendar"]});setOpen(false)}})
  const management=["ADMIN","CEO","SALES_HEAD","HR","MANAGEMENT","DEPARTMENT_HEAD"].includes(user?.role)
  return <div><PageHeader title="Company Calendar" subtitle="One calendar for birthdays, leave, deadlines, holidays and company events." backTo="/" actions={management?<button onClick={()=>setOpen(true)} className="pill-accent inline-flex items-center gap-2 px-4 py-2.5 text-xs"><Plus size={15}/> Add event</button>:null}/>
    <div className="grid gap-5 lg:grid-cols-[1.5fr_.7fr]">
      <div className="card p-5"><div className="flex items-center justify-between"><button onClick={()=>setCursor(new Date(year,month-1,1))} className="rounded-xl p-2 hover:bg-surface-2"><ChevronLeft size={18}/></button><div className="text-center"><p className="text-lg font-semibold text-ink">{cursor.toLocaleDateString(undefined,{month:"long",year:"numeric"})}</p><p className="text-xs text-muted">{q.data?.calendar?.length||0} events this month</p></div><button onClick={()=>setCursor(new Date(year,month+1,1))} className="rounded-xl p-2 hover:bg-surface-2"><ChevronRight size={18}/></button></div>
      <div className="mt-5 grid grid-cols-7 gap-2 text-center text-[10px] font-semibold uppercase text-muted">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><div key={d} className="py-2">{d}</div>)}{cells.map((day,i)=>{const key=day?`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`:"";const events=byDate[key]||[];return <button key={i} disabled={!day} onClick={()=>events.length&&setSelected({date:key,events})} className={`min-h-24 rounded-2xl border p-2 text-left ${day?"border-border hover:border-accent/40":"border-transparent"} ${events.length?"bg-accent/5":""}`}><span className="text-xs font-semibold text-ink">{day||""}</span>{events.slice(0,3).map(e=><span key={e.id} className="mt-1 block truncate rounded-lg bg-surface-2 px-1.5 py-1 text-[9px] text-muted">{e.title}</span>)}{events.length>3&&<span className="text-[9px] text-accent">+{events.length-3} more</span>}</button>})}</div></div>
      <div className="card p-5"><div className="flex items-center gap-2"><CalendarDays size={18} className="text-accent"/><h3 className="font-semibold text-ink">Event feed</h3></div><div className="mt-4 space-y-2">{(q.data?.events||[]).map(e=><button key={e.id} onClick={()=>setSelected({date:e.date,events:[e]})} className="w-full rounded-2xl bg-surface-2 p-3 text-left hover:bg-surface-3"><p className="text-xs font-semibold text-ink">{e.title}</p><p className="mt-1 text-[10px] text-muted">{fmt(e.date)} · {TYPES[e.type]||e.type}</p></button>)}{!q.data?.events?.length&&<p className="text-sm text-muted">No events in this month.</p>}</div></div>
    </div>
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={()=>setSelected(null)}><div onClick={e=>e.stopPropagation()} className="w-full max-w-md rounded-3xl bg-surface p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-lg font-semibold text-ink">{fmt(selected.date)}</p><p className="text-xs text-muted">{selected.events.length} event(s)</p></div><button onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="mt-5 space-y-3">{selected.events.map(e=><div key={e.id} className="rounded-2xl bg-surface-2 p-4"><p className="text-sm font-semibold text-ink">{e.title}</p><p className="mt-1 text-xs text-muted">{TYPES[e.type]||e.type}</p>{e.description&&<p className="mt-2 text-xs leading-5 text-muted">{e.description}</p>}</div>)}</div></div></div>}
    {open&&<EventModal onClose={()=>setOpen(false)} onSave={form=>create.mutate(form)} pending={create.isPending}/>}</div>
}
function EventModal({onClose,onSave,pending}){const [form,setForm]=useState({title:"",date:"",description:"",type:"ANNUAL_EVENT",isAnnual:true});return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form onSubmit={e=>{e.preventDefault();if(form.title&&form.date)onSave(form)}} className="w-full max-w-md rounded-3xl bg-surface p-6 shadow-2xl"><div className="flex justify-between"><h3 className="text-lg font-semibold text-ink">Add company event</h3><button type="button" onClick={onClose}><X size={18}/></button></div><div className="mt-5 space-y-4"><input className="field w-full" placeholder="Event title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input className="field w-full" type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><select className="field w-full" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="ANNUAL_EVENT">Company event</option><option value="NATIONAL_HOLIDAY">Holiday</option></select><textarea className="field min-h-24 w-full" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label className="flex items-center gap-2 text-xs text-muted"><input type="checkbox" checked={form.isAnnual} onChange={e=>setForm({...form,isAnnual:e.target.checked})}/> Repeat every year</label></div><button disabled={pending} className="pill-accent mt-5 w-full px-4 py-2.5 text-xs">{pending?"Saving…":"Save event"}</button></form></div>}
