import { useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Clock3, Plus, Trash2, X } from "lucide-react"
import api from "../api/client"
import PageHeader from "../components/ui/PageHeader"
import { isManagement } from "../utils/roles"
import { useAuth } from "../context/AuthContext"

export default function Timesheets() {
  const { user } = useAuth(); const management = isManagement(user?.role); const qc = useQueryClient(); const today = new Date().toISOString().slice(0,10)
  const [showForm,setShowForm]=useState(false); const [employeeId,setEmployeeId]=useState(""); const [form,setForm]=useState({date:today,projectId:"",taskId:"",hours:"",note:""})
  const {data:rows=[]}=useQuery({queryKey:["timesheets",employeeId],queryFn:()=>api.get("/timesheets",{params:{employeeId:employeeId||undefined}}).then(r=>r.data)})
  const {data:employees=[]}=useQuery({queryKey:["employees","timesheets"],queryFn:()=>api.get("/employees",{params:{page:1,pageSize:100}}).then(r=>r.data?.data||[]),enabled:management})
  const {data:projects=[]}=useQuery({queryKey:["projects","timesheets"],queryFn:()=>api.get("/projects").then(r=>r.data)})
  const {data:tasks=[]}=useQuery({queryKey:["tasks","timesheets",form.projectId],queryFn:()=>api.get("/tasks",{params:{projectId:form.projectId}}).then(r=>r.data),enabled:!!form.projectId})
  const add=useMutation({mutationFn:()=>api.post("/timesheets",{...form,hours:Number(form.hours),projectId:form.projectId||null,taskId:form.taskId||null}),onSuccess:()=>{qc.invalidateQueries({queryKey:["timesheets"]});qc.invalidateQueries({queryKey:["tasks"]});setForm({date:today,projectId:"",taskId:"",hours:"",note:""});setShowForm(false)}})
  const remove=useMutation({mutationFn:id=>api.delete(`/timesheets/${id}`),onSuccess:()=>{qc.invalidateQueries({queryKey:["timesheets"]});qc.invalidateQueries({queryKey:["tasks"]})}})
  const total=rows.reduce((sum,r)=>sum+Number(r.hours||0),0)
  return <div className="space-y-5"><PageHeader title="Timesheets" subtitle="Record project and task hours without losing the work history." actions={<button onClick={()=>setShowForm(v=>!v)} className="pill-accent flex items-center gap-2 px-4 py-2.5 text-sm">{showForm?<X size={15}/>:<Plus size={15}/>} {showForm?"Cancel":"Log time"}</button>}/>
    <div className="grid gap-4 sm:grid-cols-3"><div className="card p-5"><p className="text-xs text-muted">Entries</p><p className="mt-2 text-2xl font-semibold text-ink">{rows.length}</p></div><div className="card p-5"><p className="text-xs text-muted">Total hours</p><p className="mt-2 text-2xl font-semibold text-ink">{total.toFixed(2)}</p></div><div className="card p-5"><p className="text-xs text-muted">Access</p><p className="mt-2 text-sm font-semibold text-ink">{management?"Management + your entries":"Your entries"}</p></div></div>
    {showForm&&<form onSubmit={e=>{e.preventDefault();add.mutate()}} className="card grid gap-4 p-5 sm:grid-cols-2"><label><span className="text-xs font-semibold text-muted">Date</span><input required type="date" className="field mt-1 w-full" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label><span className="text-xs font-semibold text-muted">Hours</span><input required min="0.25" max="24" step="0.25" type="number" className="field mt-1 w-full" value={form.hours} onChange={e=>setForm({...form,hours:e.target.value})}/></label><label><span className="text-xs font-semibold text-muted">Project</span><select className="field mt-1 w-full" value={form.projectId} onChange={e=>setForm({...form,projectId:e.target.value,taskId:""})}><option value="">No project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span className="text-xs font-semibold text-muted">Task</span><select className="field mt-1 w-full" value={form.taskId} onChange={e=>setForm({...form,taskId:e.target.value})} disabled={!form.projectId}><option value="">No task</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label className="sm:col-span-2"><span className="text-xs font-semibold text-muted">Note</span><input className="field mt-1 w-full" value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="What did you work on?"/></label><div className="sm:col-span-2 flex justify-end"><button disabled={add.isPending} className="pill-accent px-5 py-2.5 text-sm">{add.isPending?"Saving…":"Save entry"}</button></div>{add.isError&&<p className="sm:col-span-2 text-xs text-danger">{add.error?.response?.data?.error||"Could not save time."}</p>}</form>}
    <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="border-b border-border bg-surface-2"><tr><th className="px-5 py-3">Date</th>{management&&<th className="px-5 py-3">Employee</th>}<th className="px-5 py-3">Project</th><th className="px-5 py-3">Task</th><th className="px-5 py-3">Hours</th><th className="px-5 py-3">Note</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-border last:border-0"><td className="px-5 py-3 text-muted">{new Date(r.date).toLocaleDateString()}</td>{management&&<td className="px-5 py-3 font-medium text-ink">{r.employee?.name}</td>}<td className="px-5 py-3 font-medium text-ink">{r.project?.name||"—"}</td><td className="px-5 py-3 text-muted">{r.task?.title||"—"}</td><td className="px-5 py-3 font-semibold text-ink">{Number(r.hours).toFixed(2)}</td><td className="max-w-xs px-5 py-3 text-muted">{r.note||"—"}</td><td className="px-5 py-3 text-right"><button onClick={()=>remove.mutate(r.id)} className="rounded-full p-2 text-muted hover:bg-red-50 hover:text-danger"><Trash2 size={14}/></button></td></tr>)}{rows.length===0&&<tr><td colSpan={management?7:6} className="px-5 py-10 text-center text-muted"><Clock3 className="mx-auto mb-2" size={20}/>No time entries yet.</td></tr>}</tbody></table></div></div>
  </div>
}
